version: '3.8'

services:
  epic-games-bot:
    build: .
    container_name: epic-games-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - NOTIFICATION_CHANNEL_ID=${NOTIFICATION_CHANNEL_ID}
      - NOTIFICATION_TIME=${NOTIFICATION_TIME:-13:00}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - EPIC_GAMES_REGION=${EPIC_GAMES_REGION:-US}
      - DATABASE_PATH=/app/data/bot.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; from src.services.epic_games import EpicGamesService; asyncio.run(EpicGamesService().get_free_games())"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - monitoring

  # Optional: Add Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    profiles:
      - monitoring

volumes:
  grafana-storage: